[build]
    command = "npm run build" # or your build command
    publish = "dist" # or your build output directory

[functions]
    directory = "functions"

[[redirects]]
    from = "/*"
    to = "/.netlify/functions/main" # Adjust 'main' to your function file name
    status = 200