[build]
  command = "npm run build"
  functions = "dist/netlify/functions"     # Path to built functions directory
  publish = "public"                        # (Optional) if you have a landing page

[functions]
  node_bundler = "esbuild"
  external_node_modules = [
    "@nestjs/microservices",
    "@nestjs/websockets",
    "@nestjs/websockets/socket-module",
    "@nestjs/microservices/microservices-module"
  ]
